### ISSUE TITLE
I guess I'll try a new repo?

### ISSUE THREAD

**Issue by valeriebordeleau** [valeriebordeleau/portfolioNew#1]
@thomasjbradley

**Comment by valeriebordeleau** [comment]
I genuinely have 0.0001% understanding of what I just did but I think I fixed it. Sorry for all the notifications. I owe you a hot beverage (or 20)!

**Comment by thomasjbradley** [comment]
Okay—glad to see you figured it out.
Can't say I know exactly what you did—but good to hear it's working.
I'm happy to help any time.

**Comment by valeriebordeleau** [comment]
I believe putting everything in a new repo cleared the caches? I couldn't figure out another way to delete the auto generated icon.css file from fontastic. It doesn't show up in my local files.

**Comment by valeriebordeleau** [comment]
thanks!
