### ISSUE TITLE
extra scroll-able space on all pages

### ISSUE THREAD

**Issue by valeriebordeleau** [valeriebordeleau/portfolioNew#2]
@thomasjbradley

Any idea why I might be able to scroll to the right with a ton of extra space on all pages? There's no element there for me to inspect...

Thanks!

**Comment by valeriebordeleau** [comment]
Fixed it with an overflow hidden.
Thanks again

**Comment by valeriebordeleau** [comment]
would 

overflow-x: hidden;

cause any other complications?

**Comment by thomasjbradley** [comment]
Yeah `overflow-x: hidden` would work really well—add it to `<body>`.
I don't think it'll have any negative side-effects.

**Comment by valeriebordeleau** [comment]
Sweet. Thanks!

**Comment by valeriebordeleau** [comment]
Would I need any kind of vendor prefix or anything like that to support this on mobile? On chrome for android (version 54.0), I still have the extra space. Thanks!

**Comment by valeriebordeleau** [comment]
Vendor prefix did some magic and now problem is gone.
